# Generated by Django 5.2.6 on 2025-11-23 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('external_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='jokes', to='chuck_jokes.category')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_jokes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
